import React, { useEffect, useMemo, useState } from 'react';
import { Booking, Equipment, FarmerField, User } from '../types';
import { Calendar, Camera, CheckCircle2, Edit3, MapPin, Plus, Receipt, RefreshCw, Sprout, Tractor, Trash2 } from 'lucide-react';
import { EquipmentCard } from '../components/EquipmentCard';
import { fetchEquipmentList } from '../services/api';

interface FarmerDashboardProps { currentUser: User; bookings: Booking[]; onOpenInvoice: (booking: Booking) => void; onOpenBooking: (equipment: Equipment) => void; onSelectEquipment: (equipment: Equipment) => void; onUpdateUser: (user: User) => void; }
const keyFor = (userId: string) => `velantech_fields_${userId}`;
const defaultField = (user: User): FarmerField => ({ id: `field-${Date.now()}`, name: 'Main Farm', location: user.address.formattedAddress || user.address.village, village: user.address.village, district: user.address.district, state: user.address.state, pincode: user.address.pincode, areaAcres: user.farmerDetails?.landSizeAcres || 0, crop: user.farmerDetails?.primaryCrops?.[0] || '' });

export const FarmerDashboard: React.FC<FarmerDashboardProps> = ({ currentUser, bookings, onOpenInvoice, onOpenBooking, onSelectEquipment, onUpdateUser }) => {
  const [tab, setTab] = useState<'overview' | 'equipment' | 'rentals' | 'profile'>('overview'); const [fields, setFields] = useState<FarmerField[]>([]); const [editing, setEditing] = useState<FarmerField | null>(null); const [equipment, setEquipment] = useState<(Equipment & { distanceKm?: number })[]>([]); const [loading, setLoading] = useState(false);
  const myBookings = useMemo(() => bookings.filter((item) => item.farmerId === currentUser.id || item.farmerName === currentUser.name), [bookings, currentUser]); const activeBookings = myBookings.filter((item) => ['Approved', 'En Route', 'In Use'].includes(item.bookingStatus)); const acres = fields.reduce((total, field) => total + Number(field.areaAcres || 0), 0);
  useEffect(() => { try { setFields(JSON.parse(localStorage.getItem(keyFor(currentUser.id)) || '[]')); } catch { setFields([]); } }, [currentUser.id]);
  const saveFields = (next: FarmerField[]) => { setFields(next); localStorage.setItem(keyFor(currentUser.id), JSON.stringify(next)); };
  const loadEquipment = async () => { setLoading(true); setEquipment(await fetchEquipmentList({ categoryId: 'all', search: '', userLat: currentUser.address.latitude || 11.0168, userLng: currentUser.address.longitude || 76.9558, radiusKm: 100, fuelType: 'all', minHp: 0, availability: 'Available', sortBy: 'distance', includeUnapproved: false })); setLoading(false); };
  useEffect(() => { void loadEquipment(); }, [currentUser.id]);
  const uploadAvatar = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => onUpdateUser({ ...currentUser, avatar: String(reader.result) }); reader.readAsDataURL(file); };
  const saveField = () => { if (!editing || !editing.name.trim() || !editing.village.trim() || !editing.areaAcres) return; saveFields(fields.some((item) => item.id === editing.id) ? fields.map((item) => item.id === editing.id ? editing : item) : [...fields, editing]); setEditing(null); };
  const fieldCards = <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{fields.map((field) => <article key={field.id} className="farmer-field-card"><div><span><MapPin /> {field.district}</span><h4>{field.name}</h4><p>{field.village}, {field.state} · {field.areaAcres} acres</p><strong>{field.crop || 'Crop not added'}</strong></div><div className="flex gap-1"><button onClick={() => setEditing(field)} aria-label={`Edit ${field.name}`}><Edit3 /></button><button onClick={() => saveFields(fields.filter((item) => item.id !== field.id))} aria-label={`Delete ${field.name}`}><Trash2 /></button></div></article>)}</div>;
  return <div className="farmer-dashboard space-y-5">
    <section className="farmer-welcome"><div className="farmer-avatar"><img src={currentUser.avatar || '/images/madu.jpg'} alt={currentUser.name} /><label title="Change profile photo"><Camera /><input type="file" accept="image/*" onChange={(e) => uploadAvatar(e.target.files?.[0])} /></label></div><div><div className="flex items-center gap-2"><h2>Welcome back, {currentUser.name.split(' ')[0]}</h2><span className="farmer-verified"><CheckCircle2 /> Verified farmer</span></div><p><MapPin /> {currentUser.address.village}, {currentUser.address.district} · {currentUser.phone}</p></div><button className="farmer-primary" onClick={() => setTab('equipment')}><Tractor /> Find equipment</button></section>
    <section className="farmer-stats"><button onClick={() => setTab('overview')}><Sprout /><b>{fields.length}</b><span>My Fields</span></button><button onClick={() => setTab('rentals')}><Calendar /><b>{myBookings.length}</b><span>Upcoming Rentals</span></button><button onClick={() => setTab('rentals')}><Tractor /><b>{activeBookings.length}</b><span>Active Rentals</span></button><button onClick={() => setTab('overview')}><MapPin /><b>{acres || 0}</b><span>Total Acres</span></button></section>
    <nav className="farmer-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>My Fields</button><button className={tab === 'equipment' ? 'active' : ''} onClick={() => setTab('equipment')}>Nearby Equipment</button><button className={tab === 'rentals' ? 'active' : ''} onClick={() => setTab('rentals')}>Upcoming Rentals</button><button className={tab === 'profile' ? 'active' : ''} onClick={() => setTab('profile')}>Farmer Profile</button></nav>
    {tab === 'overview' && <section className="farmer-panel"><div className="farmer-panel-head"><div><span>FARM OPERATIONS</span><h3>My Fields</h3><p>Add fields once, then select the exact work location while booking machinery.</p></div><button className="farmer-primary" onClick={() => setEditing(defaultField(currentUser))}><Plus /> Add Field</button></div>{fields.length ? fieldCards : <div className="farmer-empty"><Sprout /><h4>No field added yet</h4><p>Add your first field to choose it during equipment booking.</p><button className="farmer-primary" onClick={() => setEditing(defaultField(currentUser))}><Plus /> Add Field</button></div>}</section>}
    {tab === 'equipment' && <section className="space-y-4"><div className="farmer-panel-head"><div><span>RENT MACHINERY</span><h3>Find Equipment Near You</h3><p>Compare available machinery, distance, price and provider rating.</p></div><button className="farmer-outline" onClick={() => void loadEquipment()} disabled={loading}><RefreshCw className={loading ? 'animate-spin' : ''} /> Refresh</button></div>{loading ? <div className="farmer-empty">Loading nearby machinery…</div> : <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">{equipment.map((item) => <EquipmentCard key={item.id} equipment={item} currentUser={currentUser} onSelectEquipment={onSelectEquipment} onOpenBookingModal={onOpenBooking} />)}</div>}</section>}
    {tab === 'rentals' && <section className="farmer-panel"><div className="farmer-panel-head"><div><span>BOOKING TRACKER</span><h3>Upcoming Rentals</h3></div></div>{myBookings.length ? <div className="space-y-3">{myBookings.map((booking) => <article className="farmer-rental" key={booking.id}><img src={booking.equipmentImage || '/images/tractor.jpg'} alt="" /><div><span>{booking.bookingStatus}</span><h4>{booking.equipmentName}</h4><p>{booking.startDate} · {booking.startTime} · {booking.rentalDurationHours} hours</p><p><MapPin /> {booking.farmerAddress.village}, {booking.farmerAddress.district}</p></div><strong>₹{booking.totalAmount.toLocaleString('en-IN')}</strong><button className="farmer-outline" onClick={() => onOpenInvoice(booking)}><Receipt /> View booking</button></article>)}</div> : <div className="farmer-empty"><Calendar /><h4>No upcoming rentals</h4><button className="farmer-primary" onClick={() => setTab('equipment')}>Find Equipment</button></div>}</section>}
    {tab === 'profile' && <section className="farmer-panel"><div className="farmer-panel-head"><div><span>FARMER PROFILE</span><h3>Your farming details</h3></div><label className="farmer-outline cursor-pointer"><Camera /> Edit photo<input className="hidden" type="file" accept="image/*" onChange={(e) => uploadAvatar(e.target.files?.[0])} /></label></div><div className="farmer-profile-grid"><div><b>Contact</b><p>{currentUser.phone}</p></div><div><b>Village & district</b><p>{currentUser.address.village}, {currentUser.address.district}</p></div><div><b>Fields</b><p>{fields.length} field{fields.length === 1 ? '' : 's'} · {acres} acres</p></div><div><b>Main crops</b><p>{[...new Set(fields.map((field) => field.crop).filter(Boolean))].join(', ') || 'Not added yet'}</p></div></div></section>}
    {editing && <div className="fixed inset-0 z-50 grid place-items-center p-4 bg-slate-900/45"><form className="farmer-field-form" onSubmit={(e) => { e.preventDefault(); saveField(); }}><div><span>FIELD DETAILS</span><h3>{fields.some((field) => field.id === editing.id) ? 'Edit Field' : 'Add Field'}</h3></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{([['name','Field name'],['location','Work location / landmark'],['village','Village'],['district','District'],['state','State'],['pincode','Pincode'],['areaAcres','Land area (acres)'],['crop','Current crop'],['soilType','Soil type (optional)'],['irrigationType','Irrigation type (optional)']] as const).map(([name,label]) => <label key={name}>{label}<input required={['name','village','district','state','pincode','areaAcres'].includes(name)} type={name === 'areaAcres' ? 'number' : 'text'} value={editing[name] || ''} onChange={(e) => setEditing({ ...editing, [name]: name === 'areaAcres' ? Number(e.target.value) : e.target.value })} /></label>)}</div><div className="flex justify-end gap-2"><button type="button" className="farmer-outline" onClick={() => setEditing(null)}>Cancel</button><button className="farmer-primary">Save Field</button></div></form></div>}
  </div>;
};
