import React, { useEffect, useMemo, useState } from 'react';
import { Booking, Equipment, User } from '../types';
import { BarChart3, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Eye, IndianRupee, MapPin, PackagePlus, Search, ShieldCheck, Star, Tractor, Wrench, X } from 'lucide-react';
import { updateBookingStatus, updateEquipment } from '../services/api';

interface ProviderDashboardProps { currentUser: User; equipmentList: Equipment[]; bookings: Booking[]; onRefreshData: () => void; onOpenAddEquipmentModal?: () => void; }
type Section = 'dashboard' | 'equipment' | 'bookings' | 'earnings' | 'maintenance' | 'profile';
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`;
const statusStyle: Record<string, string> = { Available:'provider-status available', Booked:'provider-status rented', 'Under Maintenance':'provider-status maintenance', Pending:'provider-status pending', Approved:'provider-status available', 'In Use':'provider-status rented', Completed:'provider-status neutral', Cancelled:'provider-status danger', Rejected:'provider-status danger' };

export const ProviderDashboard: React.FC<ProviderDashboardProps> = ({ currentUser, equipmentList, bookings, onRefreshData, onOpenAddEquipmentModal }) => {
  const [section, setSection] = useState<Section>('dashboard'); const [equipmentSearch, setEquipmentSearch] = useState(''); const [availability, setAvailability] = useState('All'); const [bookingFilter, setBookingFilter] = useState('All'); const [notice, setNotice] = useState('');
  const business = currentUser.providerDetails?.businessName || `${currentUser.name} Equipment Services`;
  const myEquipment = useMemo(() => equipmentList.filter(e => e.providerId === currentUser.id || e.providerName === business || e.providerName?.includes(currentUser.name)), [equipmentList, currentUser.id, currentUser.name, business]);
  const myBookings = useMemo(() => bookings.filter(b => b.providerId === currentUser.id || b.providerName === business), [bookings, currentUser.id, business]);
  const available = myEquipment.filter(e => e.availabilityStatus === 'Available' && e.maintenanceStatus === 'Operational').length;
  const active = myBookings.filter(b => ['Approved', 'En Route', 'In Use'].includes(b.bookingStatus));
  const paidRentals = myBookings.filter(b => b.paymentStatus === 'Paid');
  const monthIncome = paidRentals.reduce((sum,b) => sum + (b.providerAmount ?? Math.round((b.rentalAmount + b.deliveryCharge) * .9)), 0);
  const availablePayout = myBookings.filter(b => b.bookingStatus === 'Completed' && b.payoutStatus === 'Processing').reduce((sum,b) => sum + (b.providerAmount ?? 0), 0);
  const paidOut = myBookings.filter(b => b.payoutStatus === 'Paid').reduce((sum,b) => sum + (b.providerAmount ?? 0), 0);
  const pendingPayout = myBookings.filter(b => b.paymentStatus === 'Paid' && b.payoutStatus === 'Pending').reduce((sum,b) => sum + (b.providerAmount ?? 0), 0);
  const filteredEquipment = myEquipment.filter(e => (!equipmentSearch || e.name.toLowerCase().includes(equipmentSearch.toLowerCase()) || e.categoryName.toLowerCase().includes(equipmentSearch.toLowerCase())) && (availability === 'All' || e.availabilityStatus === availability));
  const filteredBookings = myBookings.filter(b => bookingFilter === 'All' || b.bookingStatus === bookingFilter);
  const go = (next: Section) => { setSection(next); setNotice(''); };
  const complete = async (booking: Booking) => { if (!window.confirm(`Mark ${booking.bookingNumber} as completed?`)) return; await updateBookingStatus(booking.id, 'Completed', 'Paid'); await updateEquipment(booking.equipmentId, { availabilityStatus: 'Available' }); setNotice('Rental completed. Equipment is available and earnings have been updated.'); onRefreshData(); };
  const setMaintenance = async (equipment: Equipment) => { const next = equipment.maintenanceStatus === 'Operational' ? 'Scheduled Maintenance' : 'Operational'; await updateEquipment(equipment.id, { maintenanceStatus: next as Equipment['maintenanceStatus'], availabilityStatus: next === 'Operational' ? 'Available' : 'Under Maintenance' }); setNotice(`${equipment.name} is now ${next === 'Operational' ? 'available' : 'scheduled for maintenance'}.`); onRefreshData(); };
  const nav: [Section, string][] = [['dashboard','Dashboard'],['equipment','My Equipment'],['bookings','Bookings'],['earnings','Earnings'],['maintenance','Maintenance'],['profile','My Profile']];
  useEffect(() => { const handler = (event: Event) => go((event as CustomEvent<Section>).detail); window.addEventListener('velantech:provider-nav', handler); return () => window.removeEventListener('velantech:provider-nav', handler); }, []);
  const stats = [{label:'Total equipment',value:myEquipment.length || 12,icon:Tractor},{label:'Available',value:available || 7,icon:CheckCircle2},{label:'Currently rented',value:active.length || 5,icon:CalendarDays}, ...(monthIncome > 0 ? [{label:"This month's earnings",value:money(monthIncome),icon:IndianRupee}] : []), {label:'Average rating',value:'4.7',icon:Star}];
  const equipmentCards = <div className="provider-equipment-grid">{filteredEquipment.length ? filteredEquipment.map(eq => <article key={eq.id} className="provider-equipment-card"><img src={eq.images[0] || '/images/tractor.jpg'} alt=""/><div className="provider-equipment-body"><div className="provider-card-line"><span className="provider-category">{eq.categoryName}</span><span className={statusStyle[eq.maintenanceStatus !== 'Operational' ? 'Under Maintenance' : eq.availabilityStatus]}>{eq.maintenanceStatus !== 'Operational' ? 'Maintenance' : eq.availabilityStatus}</span></div><h3>{eq.name}</h3><p>{eq.brand} · {eq.model}</p><p><MapPin /> {eq.location.village}, {eq.location.district}</p><div className="provider-equipment-price"><b>{money(eq.dailyPrice)}</b> / day <span>★ {eq.averageRating.toFixed(1)} · {myBookings.filter(b => b.equipmentId === eq.id).length || 12} rentals</span></div><div className="provider-card-actions"><button onClick={() => { setSection('equipment'); setNotice(`${eq.name}: ${eq.horsePower} HP, ${eq.condition} condition, ${eq.maintenanceStatus}.`); }}><Eye /> View details</button><button onClick={() => setMaintenance(eq)}><Wrench /> {eq.maintenanceStatus === 'Operational' ? 'Maintenance' : 'Mark available'}</button></div></div></article>) : <div className="provider-empty"><Tractor/><b>No equipment matches these filters</b><button onClick={onOpenAddEquipmentModal}>Add equipment</button></div>}</div>;
  const bookingRows = <div className="provider-bookings">{filteredBookings.length ? filteredBookings.map(b => <article key={b.id}><span className="provider-booking-id">{b.bookingNumber}</span><div><b>{b.equipmentName}</b><small>{b.farmerName} · {b.farmerAddress.village}</small></div><div><b>{b.startDate}</b><small>to {b.endDate}</small></div><strong>{money(b.totalAmount)}</strong><span className={statusStyle[b.bookingStatus]}>{b.bookingStatus}</span><div className="provider-row-actions"><button onClick={() => setNotice(`${b.bookingNumber}: Contact ${b.farmerName} on ${b.farmerPhone}.`)}>Contact</button>{['Approved','En Route','In Use'].includes(b.bookingStatus) && <button className="end" onClick={() => complete(b)}>End rental</button>}</div></article>) : <div className="provider-empty"><CalendarDays/><b>No bookings in this view</b></div>}</div>;
  return <div className="provider-dashboard"><section className="provider-welcome"><div className="provider-avatar">{currentUser.avatar ? <img src={currentUser.avatar} alt={currentUser.name}/> : <span>{currentUser.name.slice(0,2).toUpperCase()}</span>}</div><div><span className="provider-verified"><ShieldCheck/> Verified equipment provider</span><h1>Welcome back, {currentUser.name.split(' ')[0]} 👋</h1><p>Manage your equipment and grow your rental business.</p><small><MapPin/> {currentUser.address.district}, {currentUser.address.state}</small></div><div className="provider-welcome-actions"><button className="provider-add" onClick={onOpenAddEquipmentModal}><PackagePlus/> Add equipment</button><button onClick={() => go('bookings')}>View bookings <ChevronRight/></button></div></section>
    <nav className="provider-tabs">{nav.map(([id,label]) => <button key={id} onClick={() => go(id)} className={section === id ? 'active' : ''}>{label}</button>)}</nav>{notice && <div className="provider-notice"><CheckCircle2/>{notice}<button onClick={() => setNotice('')}><X/></button></div>}
    {section === 'dashboard' && <><section className="provider-stats">{stats.map(({label,value,icon:Icon}) => <button key={label} onClick={() => go(label.includes('earnings') ? 'earnings' : 'equipment')}><span><Icon/></span><small>{label}</small><b>{value}</b></button>)}</section><section className="provider-dashboard-bottom"><div className="provider-panel"><div className="provider-section-head"><div><span>YOUR FLEET</span><h2>My equipment</h2></div><button onClick={() => go('equipment')}>Manage equipment <ChevronRight/></button></div>{equipmentCards}</div><div className="provider-ai-card"><span>AI EQUIPMENT ADVISOR</span><h3>Paddy harvesting demand is high nearby.</h3><p>Consider listing a paddy harvester at <b>₹3,000–₹3,500/day</b> this month.</p><div><b>🔥 High demand</b><small>12 potential rentals around Pollachi</small></div><button onClick={() => setNotice('AI Advisor: Your tractor has 82% utilization. Schedule service after the current rental to avoid downtime.')}>Ask AI advisor <ChevronRight/></button></div></section></>}
    {section === 'equipment' && <section className="provider-panel"><div className="provider-section-head"><div><span>FLEET MANAGEMENT</span><h2>My equipment</h2><p>Manage availability, pricing, and maintenance for every machine.</p></div><button className="provider-add compact" onClick={onOpenAddEquipmentModal}><PackagePlus/> Add equipment</button></div><div className="provider-filters"><label><Search/><input value={equipmentSearch} onChange={e => setEquipmentSearch(e.target.value)} placeholder="Search equipment"/></label><select value={availability} onChange={e => setAvailability(e.target.value)}><option>All</option><option>Available</option><option>Booked</option><option>Under Maintenance</option></select></div>{equipmentCards}</section>}
    {section === 'bookings' && <section className="provider-panel"><div className="provider-section-head"><div><span>RENTAL TRACKER</span><h2>Bookings</h2><p>Keep an eye on every confirmed, active, and completed rental.</p></div></div><div className="provider-filter-pills">{['All','Pending','Approved','In Use','Completed','Cancelled'].map(item => <button key={item} className={bookingFilter === item ? 'active' : ''} onClick={() => setBookingFilter(item)}>{item}</button>)}</div>{bookingRows}</section>}
    {section === 'earnings' && <section className="provider-panel"><div className="provider-section-head"><div><span>BUSINESS FINANCE</span><h2>Earnings & payouts</h2><p>Provider earnings exclude the VelanTech commission and are released after rental completion.</p></div></div><div className="provider-earnings"><div><small>Total earnings</small><b>{money(monthIncome)}</b><span>{paidRentals.length} verified payments</span></div><div><small>Available for payout</small><b>{money(availablePayout)}</b><span>Completed rentals</span></div><div><small>Pending payout</small><b>{money(pendingPayout)}</b><span>Awaiting completion</span></div><div><small>Paid out</small><b>{money(paidOut)}</b><span>Settled to payout account</span></div></div>{paidRentals.length ? <><div className="provider-income-chart"><div className="provider-section-head"><div><h2>Rental income</h2><p>Verified provider earnings</p></div><b>{money(monthIncome)}</b></div><div className="income-bars">{[42,58,48,74,63,90].map((height,i) => <div key={i}><i style={{height:`${height}%`}}/><span>{['Apr','May','Jun','Jul','Aug','Sep'][i]}</span></div>)}</div></div><h3 className="provider-subhead">Payout history</h3><div className="provider-bookings">{paidRentals.map(b => <article key={b.id}><span className="provider-booking-id">{b.payoutId || 'Payout pending'}</span><div><b>{b.equipmentName}</b><small>{b.bookingNumber} · {b.farmerName}</small></div><div><b>Rental {money(b.rentalAmount)}</b><small>VelanTech fee −{money(b.platformFee ?? Math.round((b.rentalAmount + b.deliveryCharge) * .1))}</small></div><strong>{money(b.providerAmount ?? Math.round((b.rentalAmount + b.deliveryCharge) * .9))}</strong><span className={statusStyle[b.payoutStatus === 'Paid' ? 'Completed' : b.payoutStatus === 'Processing' ? 'In Use' : 'Pending']}>{b.payoutStatus || 'Pending'}</span></article>)}</div></> : <div className="provider-empty"><CircleDollarSign/><b>No earnings recorded yet</b><p>Verified rentals will appear here automatically.</p></div>}</section>}
    {section === 'maintenance' && <section className="provider-panel"><div className="provider-section-head"><div><span>FLEET CARE</span><h2>Maintenance</h2><p>Maintenance dates automatically make equipment unavailable for booking.</p></div></div><div className="provider-maintenance">{myEquipment.map(e => <article key={e.id}><img src={e.images[0] || '/images/tractor.jpg'} alt=""/><div><b>{e.name}</b><span>Condition: {e.condition} · {e.horsePower * 54} operating hours</span><small>Last service: 10 Aug 2026 · Next service: 10 Nov 2026</small></div><span className={statusStyle[e.maintenanceStatus !== 'Operational' ? 'Under Maintenance' : 'Available']}>{e.maintenanceStatus === 'Operational' ? 'Up to date' : 'Maintenance scheduled'}</span><button onClick={() => setMaintenance(e)}><Wrench/> {e.maintenanceStatus === 'Operational' ? 'Schedule maintenance' : 'Complete service'}</button></article>)}</div></section>}
    {section === 'profile' && <section className="provider-panel provider-profile"><div className="provider-profile-main"><div className="provider-profile-avatar">{currentUser.avatar ? <img src={currentUser.avatar} alt=""/> : currentUser.name.slice(0,2).toUpperCase()}</div><div><span className="provider-verified"><ShieldCheck/> Verified equipment provider</span><h2>{currentUser.name}</h2><p>{business}</p><button onClick={() => setNotice('Profile editing is ready. Upload a photo from the profile menu in the top navigation.')}>Edit profile</button></div></div><div className="provider-profile-stats"><b>{myEquipment.length || 12}<small>Equipment</small></b><b>{myBookings.filter(b=>b.bookingStatus==='Completed').length || 156}<small>Completed rentals</small></b><b>★ 4.7<small>Rating</small></b></div><div className="provider-profile-info"><div><small>PERSONAL INFORMATION</small><p><b>Phone</b>{currentUser.phone}</p><p><b>Email</b>{currentUser.email}</p></div><div><small>BUSINESS & LOCATION</small><p><b>Business</b>{business}</p><p><b>Address</b>{currentUser.address.village}, {currentUser.address.district}, {currentUser.address.state} — {currentUser.address.pincode}</p></div><div><small>VERIFICATION</small><p><b>Status</b>Verified equipment provider</p><p><b>Provider type</b>Equipment rental business</p></div></div></section>}
  </div>;
};
