import React, { useState } from 'react';
import { Equipment, User, Booking, FarmerField } from '../types';
import { ArrowLeft, Calendar, Check, CheckCircle2, CreditCard, MapPin, Plus, ShieldCheck, Tractor, X } from 'lucide-react';
import { createBooking, payForBooking } from '../services/api';

interface BookingModalProps { equipment: Equipment; currentUser: User; onClose: () => void; onBookingSuccess: (booking: Booking) => void; }
const fieldKey = (userId: string) => `velantech_fields_${userId}`;
const today = new Date().toISOString().slice(0, 10);

export const BookingModal: React.FC<BookingModalProps> = ({ equipment, currentUser, onClose, onBookingSuccess }) => {
  const [fields, setFields] = useState<FarmerField[]>(() => { try { return JSON.parse(localStorage.getItem(fieldKey(currentUser.id)) || '[]'); } catch { return []; } });
  const [selectedFieldId, setSelectedFieldId] = useState(''); const [step, setStep] = useState(1);
  const [startDate, setStartDate] = useState(today); const [startTime, setStartTime] = useState('07:00'); const [duration, setDuration] = useState('1');
  const [delivery, setDelivery] = useState(true); const [notes, setNotes] = useState(''); const [paymentMethod, setPaymentMethod] = useState<'UPI' | 'Cash on Delivery'>('UPI');
  const [processing, setProcessing] = useState(false); const [confirmed, setConfirmed] = useState<Booking | null>(null); const [addingField, setAddingField] = useState(false);
  const [newField, setNewField] = useState({ name: '', village: currentUser.address.village, district: currentUser.address.district, areaAcres: '' });
  const selectedField = fields.find(field => field.id === selectedFieldId); const days = Math.max(1, Number(duration) || 1);
  const rentalAmount = equipment.dailyPrice * days, deliveryCharge = delivery ? 500 : 0, gst = Math.round((rentalAmount + deliveryCharge) * .12), total = rentalAmount + deliveryCharge + equipment.depositAmount + gst;
  const steps = ['Equipment', 'Work location', 'Date & time', 'Confirm booking'];
  const addField = () => { if (!newField.name.trim() || !newField.village.trim() || !newField.areaAcres) return; const field: FarmerField = { id: `field-${Date.now()}`, name: newField.name, location: newField.village, village: newField.village, district: newField.district || currentUser.address.district, state: currentUser.address.state, pincode: currentUser.address.pincode, areaAcres: Number(newField.areaAcres), crop: '' }; const next = [...fields, field]; setFields(next); localStorage.setItem(fieldKey(currentUser.id), JSON.stringify(next)); setSelectedFieldId(field.id); setAddingField(false); };
  const confirm = async () => { if (!selectedField) return; setProcessing(true); try { const draft = await createBooking({ equipmentId: equipment.id, farmerId: currentUser.id, startDate, endDate: startDate, startTime, endTime: '18:00', rentalType: 'daily', rentalDurationHours: days * 10, rentalAmount, deliveryCharge, depositAmount: equipment.depositAmount, farmerAddress: { ...currentUser.address, village: selectedField.village, district: selectedField.district, state: selectedField.state, pincode: selectedField.pincode, formattedAddress: selectedField.location }, paymentMethod, notes }, currentUser.role); if (!draft) return; const booking = await payForBooking(draft.id); if (booking) { setConfirmed(booking); onBookingSuccess(booking); } else alert('Payment is being verified. Your booking is not confirmed yet.'); } finally { setProcessing(false); } };
  const canNext = step === 1 || (step === 2 && !!selectedField) || (step === 3 && !!startDate && !!startTime);

  if (confirmed) return <div className="booking-overlay"><section className="booking-modal booking-success"><button className="booking-close" onClick={onClose}><X /></button><div className="booking-success-icon"><CheckCircle2 /></div><span className="booking-kicker">BOOKING CONFIRMED</span><h2>Your equipment is reserved</h2><p>{equipment.name} will be arranged for <b>{selectedField?.name}</b>, {selectedField?.village}.</p><div className="booking-confirmation"><span>Booking number <b>{confirmed.bookingNumber}</b></span><span>Work area <b>{selectedField?.areaAcres} acres</b></span><span>Date & time <b>{startDate} · {startTime}</b></span><strong>₹{total.toLocaleString('en-IN')}</strong></div><button className="booking-primary" onClick={onClose}>View my rentals <Check /></button></section></div>;
  return <div className="booking-overlay"><section className="booking-modal" role="dialog" aria-modal="true" aria-label="Book equipment"><header className="booking-header"><div><span className="booking-kicker">EQUIPMENT RENTAL</span><h2>Book {equipment.name}</h2></div><button className="booking-close" onClick={onClose}><X /></button></header><div className="booking-steps">{steps.map((name, index) => <div key={name} className={step === index + 1 ? 'current' : step > index + 1 ? 'done' : ''}><i>{step > index + 1 ? <Check /> : index + 1}</i><span>{name}</span></div>)}</div><main className="booking-content">
    {step === 1 && <div className="booking-equipment"><img src={equipment.images[0] || '/images/tractor.jpg'} alt=""/><div><span className="booking-category">{equipment.categoryName}</span><h3>{equipment.name}</h3><p>{equipment.brand} · {equipment.horsePower} HP · {equipment.location.village}</p><div className="booking-rate">₹{equipment.dailyPrice.toLocaleString('en-IN')} <small>/ day</small></div></div><div className="booking-provider"><Tractor /><span>Provided by</span><b>{equipment.providerName}</b><small>★ {equipment.averageRating.toFixed(1)} rating</small></div></div>}
    {step === 2 && <div className="booking-location"><div className="booking-section-title"><MapPin /><div><h3>Select your work location</h3><p>Choose the field where this equipment will be used.</p></div></div>{fields.length ? <div className="field-picker">{fields.map(field => <button type="button" onClick={() => setSelectedFieldId(field.id)} key={field.id} className={field.id === selectedFieldId ? 'selected' : ''}><i><MapPin /></i><span><b>{field.name}</b><small>{field.location || field.village}, {field.district}</small><em>{field.areaAcres} acres {field.crop ? `· ${field.crop}` : ''}</em></span>{field.id === selectedFieldId && <CheckCircle2 />}</button>)}</div> : <div className="booking-empty"><MapPin /><b>No field added yet</b><p>Add a work location to continue with this booking.</p></div>}<button className="booking-add-field" onClick={() => setAddingField(!addingField)}><Plus /> Add new field</button>{addingField && <div className="booking-mini-form"><input placeholder="Field name" value={newField.name} onChange={e => setNewField({...newField, name: e.target.value})}/><input placeholder="Village" value={newField.village} onChange={e => setNewField({...newField, village: e.target.value})}/><input placeholder="Area in acres" type="number" value={newField.areaAcres} onChange={e => setNewField({...newField, areaAcres: e.target.value})}/><button type="button" onClick={addField}>Save field</button></div>}</div>}
    {step === 3 && <div className="booking-schedule"><div className="booking-section-title"><Calendar /><div><h3>Choose date & time</h3><p>Set when you need the equipment at your field.</p></div></div><div className="booking-form-grid"><label>Booking date<input min={today} type="date" value={startDate} onChange={e => setStartDate(e.target.value)}/></label><label>Start time<input type="time" value={startTime} onChange={e => setStartTime(e.target.value)}/></label><label>Rental duration<select value={duration} onChange={e => setDuration(e.target.value)}><option value="1">1 day</option><option value="2">2 days</option><option value="3">3 days</option><option value="7">1 week</option></select></label></div><label className="delivery-toggle"><input type="checkbox" checked={delivery} onChange={e => setDelivery(e.target.checked)}/><span><b>Deliver to my field</b><small>Our partner will bring it to {selectedField?.village} · ₹500</small></span></label><label className="booking-notes">Instructions for the operator<textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Landmark, crop details, or access instructions (optional)"/></label></div>}
    {step === 4 && <div className="booking-review"><div className="booking-section-title"><ShieldCheck /><div><h3>Review & pay securely</h3><p>The final amount and provider earnings are calculated on the server.</p></div></div><div className="booking-review-card"><div><span>Equipment</span><b>{equipment.name}</b></div><div><span>Provider</span><b>{equipment.providerName}</b></div><div><span>Field / location</span><b>{selectedField?.name} · {selectedField?.village}</b><small>{days} day rental</small></div></div><div className="booking-price"><span>Rental ({days} day{days > 1 ? 's' : ''}) <b>₹{rentalAmount.toLocaleString('en-IN')}</b></span><span>Delivery <b>₹{deliveryCharge.toLocaleString('en-IN')}</b></span><span>Refundable deposit <b>₹{equipment.depositAmount.toLocaleString('en-IN')}</b></span><span>GST <b>₹{gst.toLocaleString('en-IN')}</b></span><strong>Total payable <b>₹{total.toLocaleString('en-IN')}</b></strong></div><div className="payment-choice"><CreditCard /><button onClick={() => setPaymentMethod('UPI')} className={paymentMethod === 'UPI' ? 'selected' : ''}>UPI</button><button onClick={() => setPaymentMethod('Cash on Delivery')} className={paymentMethod === 'Cash on Delivery' ? 'selected' : ''}>Pay at pickup</button></div></div>}
  </main><footer className="booking-footer">{step > 1 ? <button className="booking-back" onClick={() => setStep(step - 1)}><ArrowLeft /> Back</button> : <span/>}{step < 4 ? <button className="booking-primary" disabled={!canNext} onClick={() => setStep(step + 1)}>Continue <Check /></button> : <button className="booking-primary" disabled={processing} onClick={confirm}>{processing ? 'Confirming…' : `Confirm & pay ₹${total.toLocaleString('en-IN')}`}</button>}</footer></section></div>;
};
