import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, Search, Clock, ExternalLink, Newspaper, Landmark, RefreshCw, MapPin, Languages, AlertCircle, Sprout, ChevronRight } from 'lucide-react';
import { KnowledgeArticle } from '../types';

interface KnowledgeCenterProps { articles: KnowledgeArticle[]; }
type NewsItem = { id: string; title: string; summary: string; source: string; sourceUrl: string; publishedAt?: string; fetchedAt: string; language: 'en' | 'ta'; category: string; state: 'india' | 'tamil-nadu' };
type Scheme = { id: string; name: string; description: string; government: string; state: 'india' | 'tamil-nadu'; category: string; officialUrl: string; lastVerified: string };
type Feed = { news: NewsItem[]; fetchedAt: string | null; fresh: boolean; cached: boolean };
const categories = ['All', 'India Agriculture', 'Tamil Nadu Agriculture', 'Farm Machinery', 'MSP & Market Prices', 'Government Schemes', 'Weather & Climate', 'Crop Advisory', 'AgriTech', 'ICAR & Research'];
const districts = ['Coimbatore', 'Chennai', 'Erode', 'Salem', 'Tiruppur', 'Madurai', 'Thanjavur', 'Trichy', 'Tirunelveli', 'Dindigul', 'Namakkal'];
const ago = (date?: string | null) => { const value = date ? new Date(date).getTime() : 0; const minutes = Math.max(0, Math.round((Date.now() - value) / 60000)); return !value ? 'date unavailable' : minutes < 60 ? `${minutes || 1} min ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(value)); };

export const KnowledgeCenter: React.FC<KnowledgeCenterProps> = ({ articles }) => {
  const [search, setSearch] = useState(''); const [state, setState] = useState<'all' | 'india' | 'tamil-nadu'>('all'); const [language, setLanguage] = useState<'both' | 'en' | 'ta'>('both'); const [category, setCategory] = useState('All'); const [district, setDistrict] = useState('Coimbatore');
  const [feed, setFeed] = useState<Feed | null>(null); const [schemes, setSchemes] = useState<Scheme[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); const params = new URLSearchParams({ limit: '12' }); if (state !== 'all') params.set('state', state); if (language !== 'both') params.set('language', language); if (category !== 'All') params.set('category', category); if (search.trim()) params.set('q', search.trim()); try { const [newsResponse, schemeResponse] = await Promise.all([fetch(`/api/news?${params}`), fetch(`/api/schemes${state === 'all' ? '' : `?state=${state}`}`)]); if (!newsResponse.ok || !schemeResponse.ok) throw new Error('The information service is temporarily unavailable.'); const nextFeed: Feed = await newsResponse.json(); setFeed(nextFeed); setSchemes(await schemeResponse.json()); if (!nextFeed.fresh) setError(nextFeed.cached ? 'News refresh is temporarily unavailable. Showing recently cached verified updates.' : 'Unable to fetch the latest verified updates. Please retry shortly.'); } catch (err) { setFeed(null); setSchemes([]); setError(err instanceof Error ? err.message : 'Unable to fetch the latest verified updates.'); } finally { setLoading(false); } }, [category, language, search, state]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), search ? 350 : 0); return () => window.clearTimeout(timer); }, [load, search]);
  const guides = useMemo(() => articles.filter((article) => `${article.title} ${article.summary} ${article.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())).slice(0, 3), [articles, search]);
  return <div className="space-y-6">
    <section className="knowledge-hero rounded-3xl p-6 sm:p-8 text-white overflow-hidden"><div className="relative max-w-3xl"><span className="knowledge-eyebrow"><BookOpen className="w-3.5 h-3.5" /> VELANTECH KNOWLEDGE CENTER</span><h2>Kisan Portal & <em>Machinery Academy</em></h2><p>Verified agriculture information for India and Tamil Nadu. Sources, dates and official links are always visible.</p><div className="knowledge-search"><Search className="w-4 h-4" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search agriculture news, schemes, subsidies, machinery..." /></div></div></section>
    <section className="knowledge-controls"><div className="knowledge-pills"><button className={state === 'all' ? 'active' : ''} onClick={() => setState('all')}>All India</button><button className={state === 'india' ? 'active' : ''} onClick={() => setState('india')}>🇮🇳 India</button><button className={state === 'tamil-nadu' ? 'active' : ''} onClick={() => setState('tamil-nadu')}>🌾 Tamil Nadu</button></div><div className="knowledge-selects"><label><Languages /><select value={language} onChange={(e) => setLanguage(e.target.value as typeof language)}><option value="both">English + தமிழ்</option><option value="en">English</option><option value="ta">தமிழ்</option></select></label><label><MapPin /><select value={district} onChange={(e) => setDistrict(e.target.value)}>{districts.map((name) => <option key={name}>{name}</option>)}</select></label></div></section>
    <div className="knowledge-pills knowledge-categories">{categories.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div>
    <section className="knowledge-section"><div className="knowledge-section-head"><div><span className="knowledge-live"><i /> {feed?.fresh ? 'LIVE' : 'STATUS'}</span><h3>Live Agriculture News</h3><p>Verified agriculture updates from India and Tamil Nadu · {feed?.fresh ? `updated ${ago(feed.fetchedAt)}` : feed?.cached ? 'cached verified updates' : 'not connected'}</p></div><button className="knowledge-refresh" onClick={() => void load()} disabled={loading} aria-label="Refresh agriculture news"><RefreshCw className={loading ? 'animate-spin' : ''} /></button></div>{error && <div className="knowledge-notice"><AlertCircle />{error}<button onClick={() => void load()}>Retry</button></div>}<div className="knowledge-news-grid">{feed?.news.map((item) => <article className="knowledge-news-card" key={item.id}><div className="knowledge-card-meta"><span>{item.category}</span><span>{item.language === 'ta' ? 'தமிழ்' : 'English'}</span></div><h4>{item.title}</h4>{item.summary && <p>{item.summary}</p>}<footer><div><strong>{item.source}</strong><small><Clock /> {ago(item.publishedAt)} · fetched {ago(item.fetchedAt)}</small></div><a href={item.sourceUrl} target="_blank" rel="noreferrer">Read original <ExternalLink /></a></footer></article>)}</div>{!loading && !feed?.news.length && <div className="knowledge-empty"><Newspaper />No verified articles match these filters. Try another category or refresh.</div>}</section>
    <section className="knowledge-section"><div className="knowledge-section-head"><div><span className="knowledge-live schemes"><Landmark /> OFFICIAL PORTALS</span><h3>Government Schemes for Farmers</h3><p>Discover verified government schemes and support programmes. Confirm eligibility before applying.</p></div></div><div className="knowledge-scheme-grid">{schemes.map((scheme) => <article className="knowledge-scheme-card" key={scheme.id}><span>{scheme.category}</span><h4>{scheme.name}</h4><p>{scheme.description}</p><dl><dt>Government</dt><dd>{scheme.government}</dd><dt>Last verified</dt><dd>{scheme.lastVerified}</dd></dl><a href={scheme.officialUrl} target="_blank" rel="noreferrer">View official details <ChevronRight /></a></article>)}</div></section>
    <section className="knowledge-bottom-grid"><article className="knowledge-advisory"><Sprout /><div><h3>Farmer advisories</h3><p>For weather, pest and crop guidance, use the AI Agronomist with your field and crop details.</p></div></article><article className="knowledge-market"><h3>Today’s agricultural market prices</h3><p>Verified official market-price data is not configured yet. No estimates are displayed.</p><span>Selected district: {district}</span></article></section>
    {guides.length > 0 && <section className="knowledge-guides"><h3>VELANTECH field guides</h3><div>{guides.map((guide) => <article key={guide.id}><span>{guide.category}</span><h4>{guide.title}</h4><p>{guide.summary}</p></article>)}</div></section>}
  </div>;
};
